### PR TITLE
Changing the way the data is imported to be in order, not randomised 

### PR DESCRIPTION
**Pull request by A7DC**

### CODE REVIEW

**Comment by myhandleisdan** [comment]
@A7DC @TDMW 

I like the straightforward solution that you're proposing here, @A7DC. However, I think it would be best not to overwrite the initial functionality of the tool. In my mind, the best outcome is to be able to toggle between `randomized` and `ordered` from the plugin UI panel because I feel like randomized has its use-cases.

Thoughts? 😄

**Comment by A7DC** [comment]
Yeah, I did think that! Just needed to quickly find a solution while I was at work, but yes, I think having the option would be good also

**Comment by TDMW** [comment]
Seems like a very good idea! Although I completely agree on the fact that it needs to support both `random` and `ordered`. I've got some time to work on the plugin again this week and I'll make sure to use your PR-work for the `ordered` option. Thanks!

**Comment by TDMW** [comment]
@A7DC thanks for your help, I however managed to fix it in a slightly different way. A update of the plugin has been released. Let me know when this doesn't fit your needs and I'll be happy to have a look again if needed.

**Pull request closed without merging**
